### ISSUE TITLE
Integration with nanonext::random()

### ISSUE THREAD

**Issue by shikokuchuo** [paithiov909/nanoidr#53]
I have a cryptographic RNG implementation in the development version of the 'nanonext' package.
```r
install.packages("nanonext", repos = "shikokuchuo.r-universe.dev")
```

`random()` returns a random positive double. I am not finding a way to integrate it with your 'func' argument as it expects a function where you can specify the length of input as an argument.

Just wondering if there an easy way around this? If not, please feel free to close this. You have a nice implementation, I would not want to add complexity just for this specific case. Thanks.

**Comment by paithiov909** [comment]
Hi, @shikokuchuo.

I came up with the following snippet. Though I don't think this is a very good practice, it seems to work well with your `nng_random` function.

If you come up with an implementation that looks better, please let me know.

``` r
requireNamespace("nanonext", quietly = TRUE)

my_rand_gen <- \(size) {
  vec <- sapply(seq_len(size), \(len) {
    nanonext::nng_random()
  })
  abs(scale(vec) * 128 - 1)
}

plot(my_rand_gen(1000))
```

![](https://i.imgur.com/OprfzmQ.png)

``` r
nanoidr::nanoid(func = \(size) { my_rand_gen(size) })
#> [1] "irxO1JRA9JVBGDymYYjMl"
```

<sup>Created on 2022-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by shikokuchuo** [comment]
I see, thanks for the quick response! I see the size argument basically equates to the number of calls to the RNG.
`abs(scale())` does feel a bit questionable. I will have a think about how best to do this.

**Comment by shikokuchuo** [comment]
Based on your example I have created what I think is a more correct version below. The C function underlying `random()` returns a uint32t which I am able to represent fully as a double, but essentially the range will be between 0 and 2 * integer.max.

``` r
my_rand_gen <- function(size) {
  x <- numeric(size)
  for (i in seq_len(size)) x[i] <- nanonext::random()
  x / (.Machine[["integer.max"]] * 2) * 128
}
nanoidr::nanoid(size = 50L, func = my_rand_gen)
#> [1] "SfEcRMRkbmRs9QIRysDHKY2gQuRMKhRUfKS-BwMWB8rPx3T2gx"
```
<sup>Created on 2022-06-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks again for your help!

**Comment by shikokuchuo** [comment]
FYI for those coming across this, nanonext's `random()` function now takes an argument 'n' for generating a vector of random numbers. So the solution is simplified to a one-liner that just scales the output:

```r
nanoid(func = \(x) nanonext::random(x) / (.Machine[["integer.max"]] * 2) * 128)
#> [1] "EYDlgidaq92sXgqtBuUS7"
```
